name: Android UI Tests

on:
  push:
    branches: [main]
  pull_request:

jobs:
  ui-tests:
    name: Run Android UI Tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        api-level: [30]
        target: [google_apis]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Create AVD and launch emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: ${{ matrix.target }}
          arch: x86_64
          profile: pixel
          emulator-options: -no-window -no-audio -no-boot-anim
          disable-animations: true
          script: ./gradlew connectedDebugAndroidTest
