name: Internal PlayStore Build

on:
  workflow_dispatch:  # Allows manual trigger
#  push:
#    branches:
#      - main
#  pull_request:
#    branches:
#      - main

jobs:
  build:
    # runs-on: ubuntu-latest
    runs-on: self-hosted
    env:
      KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
      KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
      KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Android Environment Setup
        uses: ./.github/actions/android-setup

      # Cache Gradle dependencies to speed up builds
      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Build the APK using Gradle
      - name: Build the app
        run: ./gradlew assembleRelease bundleRelease
      # or when we don't want to store env value globally
      #        run: KEYSTORE_PASSWORD=value KEY_ALIAS=value KEY_PASSWORD=value  ./gradlew assembleRelease

      # Upload the APK as an artifact using the latest version 4
# Commented to avoid github space consumization
#      - name: Upload APK
#        uses: actions/upload-artifact@v4  # Updated to v4
#        with:
#          name: release-app-build
#          path: app/build/outputs/apk/release/app-release.apk

      - name: Upload to Google Play
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.PLAY_STORE_SERVICE_ACCOUNT_JSON }}
          packageName:  com.cicdanduitest.androiduitest
          releaseFiles: app/build/outputs/bundle/release/app-release.aab
          track: internal # ${{ secrets.PLAY_STORE_TRACK }}
#         track: production  # Can also be 'beta', 'alpha', or 'internal

